# Exceptions & Stack Traces

# This code is purposely creating an exception in order to provide an example of an error message when run
def greet(person)
  puts "hello, " + person
end 

greet("John")
greet(1)